[OPS-665] Unpin cabal hashes
serokell/serokell-closure pull request #8
Opened 2018-12-07 18:00 UTC by mkaito

Given that:

* all-cabal-hashes gets asked to be bumped every other day
* all-cabal-hashes does not delete old hashes, only adds new ones

We should probably just unpin it in  serokell-closure.

This should be completely safe, and individual projects can still override it with a pin if necessary.

2018-12-07 18:02 UTC, yorickvP commented
Are you sure this needs to be a derivation?

2018-12-07 18:05 UTC, mkaito commented
Without it, it says "this is not a derivation", so I suppose so, yes.

2018-12-10 15:49 UTC, yorickvP commented
This rebuilds the cabal names every time the all-cabal-hashes repo updates, I think.

2018-12-10 16:28 UTC, mkaito commented
That takes 70 seconds on my computer.

2018-12-17 05:59 UTC, lukateras requested changes
```
{
  all-cabal-hashes = builtins.fetchurl "https://github.com/commercialhaskell/all-cabal-hashes/archive/hackage.tar.gz";
}

2018-12-17 12:21 UTC, mkaito commented
@yegortimoshenko https://github.com/serokell/serokell-closure/pull/8#issuecomment-445315974

I already tried that.

2018-12-18 18:23 UTC, closed without merging